// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/daifukuninja/petit-misskey-go/config"
	"github.com/daifukuninja/petit-misskey-go/infrastructure/setting"
	"github.com/daifukuninja/petit-misskey-go/router"
)

// Injectors from wire.go:

func InitializeRouter() *router.Router {
	configConfig := config.NewConfig()
	userSetting := setting.NewUserSetting()
	routerRouter := router.New(configConfig, userSetting)
	return routerRouter
}
